global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-local'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'prometheus-central-federation'    
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__=~".+"}'
    static_configs:
      - targets:
        - 'localhost:9090'
    