---
# tasks file for prometheus_central_srvr
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
- name: Install utils
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - software-properties-common
    - curl
    - python3-pip
    - nfs-common
    - ansible
- name: Install botocore and boto3
  pip:
    name:
      - botocore
      - boto3
    state: present

- include_tasks: create_prom_user.yml
- include_tasks: prep_prom_directories.yml
- include_tasks: download_config.yml
- include_tasks: start_prom_svc.yml
- include_tasks: create_ami_prom_cntral.yml
