
---

- name: Add Grafana GPG key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present
    filename: grafana


- name: Run apt update
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana={{ grafana_version }}
    state: present

- name: Start Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: true




